FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY mockexchs/bitstamp/docker docker
RUN bash docker_comm/debug/setup.sh

COPY mockexchs/bitstamp/flesh/pyproject.toml pyproject.toml
COPY mockexchs/bitstamp/flesh/poetry.lock poetry.lock

# Install common
RUN pip3 install poetry
RUN poetry config settings.virtualenvs.create false

RUN poetry install
COPY mockexchs/bitstamp/flesh .
COPY comm/lib/shang /usr/local/lib/python3.7/shang
