FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY mockexchs/bitstamp/docker docker
RUN bash docker_comm/debug/setup.sh

COPY mockexchs/bitstamp/flesh/Pipfile Pipfile
COPY mockexchs/bitstamp/flesh/Pipfile.lock Pipfile.lock

# Install common
RUN pip3 install pipenv

RUN pipenv install --system
COPY mockexchs/bitstamp/flesh .
COPY comm/lib/shangren /usr/local/lib/python3.7/shangren
