FROM aux.registry.local/python-cg-ci:latest

ARG DEBIAN_VER
ARG SKAFFOLD_VER
ARG DOCKER_VER
ARG KUBECTL_VER
ARG HELM_VER

RUN apt update
RUN apt install curl wget git  -y

# Install docker
RUN apt update
RUN apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt update
RUN apt install docker-ce-cli=5:$DOCKER_VER~3-0~debian-$DEBIAN_VER -y

WORKDIR /srv

COPY . plasma

# Just to trick scripts that this is CI scenario
ENV CI_JOB_ID 1

WORKDIR /srv/plasma
RUN eval "$(./shell.py --dry-run)" && pl.bootstrap

WORKDIR /srv/plasma/citygroves
RUN eval "$(./shell.py test --dry-run)" && cg.install-deps /usr/local/bin

WORKDIR /srv
RUN rm -r *
