FROM shangren.registry.local/python-ci:latest

ARG DEBIAN_VER
ARG SKAFFOLD_VER
ARG DOCKER_VER
ARG KUBECTL_VER
ARG HELM_VER

RUN apt update
RUN apt install curl wget git  -y

# Install docker
RUN apt update
RUN apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt update
RUN apt install docker-ce-cli=5:$DOCKER_VER~3-0~debian-$DEBIAN_VER -y


RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VER/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

RUN curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v$SKAFFOLD_VER/skaffold-linux-amd64
RUN chmod +x skaffold
RUN mv skaffold /usr/local/bin

ENV HELM_NAME="helm-v$HELM_VER-linux-386"
RUN wget "https://get.helm.sh/$HELM_NAME.tar.gz"
RUN tar -zxvf "$HELM_NAME.tar.gz"
RUN mv linux-386/helm /usr/local/bin/helm
RUN rm "$HELM_NAME.tar.gz"
RUN rm -r linux-386
