
Vagrant.configure("2") do |config|
    vagrant_root = File.dirname(__FILE__)
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "dataprov" do |n|
        n.vm.hostname = "dataprov"
        n.vm.network :private_network, ip: "172.17.8.160"
    end

    config.vm.box = "bento/ubuntu-16.04"

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy.yml"
    end
end
