apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}
data:
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  DB_NAME: "{{ .Values.db.name }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_HOST: "{{ .Values.db.host }}"
  DB_PORT: "{{ .Values.db.port }}"

  GMAIL_CLIENT_ID: "{{ .Values.gmail.clientId }}"
  GMAIL_CLIENT_SECRET: "{{ .Values.gmail.clientSecret }}"
  GOOGLE_AUTH_URI: "{{ .Values.gmail.googleAuthUri }}"
  GOOGLE_TOKEN_URI: "{{ .Values.gmail.googleTokenUri }}"
  REFRESH_TOKEN: "{{ .Values.gmail.refreshToken }}"
  OWNER_EMAIL: "{{ .Values.gmail.ownerEmail }}"
