apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
