---
stages:
  - test
  - deploy-test

include:
  - '/citygroves/.gitlab-ci.yaml'

plasma.test:
#  only:
#    changes:
#      - comm
#      - .bin
#      - ./*.py
  image: aux.registry.local/python-cg-ci:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv
  before_script:
    - eval $(./shell.py --dry-run)
    - pl.bootstrap

  stage: test
  script:
    - pl.test
