apiVersion: skaffold/v1beta13
kind: Config
profiles:
  - name: local
    build:
      artifacts:
      - image: shangren/datacolls-bitstamp
        docker:
          dockerfile: datacolls/bitstamp/Dockerfile.local
        context: .
        sync:
          infer:
           - 'datacolls/bitstamp/flesh/*.py'

      - image: shangren/mockexchs-bitstamp
        docker:
          dockerfile: mockexchs/bitstamp/Dockerfile.local
        context: .
        sync:
          infer:
            - 'mockexchs/bitstamp/flesh/*.py'

      - image: shangren/tests
        docker:
          dockerfile: tests/Dockerfile.local
        context: .
        sync:
          infer:
            - 'mockexchs/bitstamp/flesh/*.py'

    deploy:
      helm:
        releases:
          - name: datacolls-bitstamp
            chartPath: datacolls/bitstamp
            namespace: datacolls
            valuesFiles:
              - datacolls/bitstamp/values/local.yaml
            values:
              image: shangren/datacolls-bitstamp

          - name: mockexchs-bitstamp
            chartPath: mockexchs/bitstamp
            namespace: mockexchs
            valuesFiles:
              - mockexchs/bitstamp/values/local.yaml
            values:
              image: shangren/mockexchs-bitstamp

          - name: tests
            chartPath: tests
            namespace: tests
            valuesFiles:
              - tests/values/local.yaml
            values:
              image: shangren/tests
