apiVersion: skaffold/v1beta13
kind: Config
profiles:
  - name: local
    build:
      artifacts:
      - image: shangren/bitstamp
        docker:
          dockerfile: dataprovs/bitstamp/Dockerfile.local
        context: ../../
        sync:
          infer:
           - 'dataprovs/bitstamp/flesh/*.py'

    deploy:
      kubectl:
        manifests:
        - k8s/app.yaml
