apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: shangren
profiles:
  - name: local
    build:
#      tagPolicy:
#        sha256: {}
      artifacts:
#      - image: shangren.registry.local/datacolls-bitstamp
#        docker:
#          dockerfile: datacolls/bitstamp/Dockerfile.local
#        context: .
#        sync:
#          infer:
#           - 'datacolls/bitstamp/flesh/*.py'
#
#      - image: shangren.registry.local/mockexchs-bitstamp
#        docker:
#          dockerfile: mockexchs/bitstamp/Dockerfile.local
#        context: .
#        sync:
#          infer:
#            - 'mockexchs/bitstamp/flesh/*.py'

      - image: shangren.registry.local/tests
        docker:
          dockerfile: tests/Dockerfile.local
        context: .
        sync:
          infer:
            - 'tests/flesh/*.py'
      local:
        push: true

    deploy:
      helm:
        releases:
#          - name: datacolls-bitstamp
#            chartPath: datacolls/bitstamp
#            namespace: datacolls
#            valuesFiles:
#              - datacolls/bitstamp/values/local.yaml
#            values:
#              image: shangren.registry.local/datacolls-bitstamp
#
#          - name: mockexchs-bitstamp
#            chartPath: mockexchs/bitstamp
#            namespace: mockexchs
#            valuesFiles:
#              - mockexchs/bitstamp/values/local.yaml
#            values:
#              image: shangren.registry.local/mockexchs-bitstamp

          - name: tests
            chartPath: tests
            namespace: tests
            valuesFiles:
              - tests/values/local.yaml
            values:
              image: shangren.registry.local/tests
