---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  telemetry:
    enabled: false
values:
  kiali:
    contextPath: /kiali
    createDemoSecret: false
    dashboard:
      grafanaURL: null
      jaegerURL: null
      passphraseKey: passphrase
      secretName: kiali
      usernameKey: username
      viewOnlyMode: false
    enabled: false
    hub: quay.io/kiali
    ingress:
      annotations: null
      enabled: false
      hosts:
        - kiali.local
      tls: null
    nodeSelector: {}
    podAntiAffinityLabelSelector: []
    podAntiAffinityTermLabelSelector: []
    prometheusNamespace: null
    replicaCount: 1
    security:
      cert_file: /kiali-cert/cert-chain.pem
      enabled: false
      private_key_file: /kiali-cert/key.pem
    tag: v1.9
