FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY tests/docker docker
RUN bash docker_comm/debug/setup.sh

COPY tests/flesh/Pipfile Pipfile
COPY tests/flesh/Pipfile.lock Pipfile.lock

# Install common
RUN pip3 install pipenv

RUN pipenv install --system
COPY mockexchs/bitstamp/flesh .
