FROM aux.registry.local/local/flesh/frontend-prebuild

WORKDIR /srv

COPY citygroves/frontend/flesh/package.json package.json
COPY citygroves/frontend/flesh/yarn.lock yarn.lock

RUN yarn install -d

COPY citygroves/frontend/flesh .