FROM node:13.5.0-stretch-slim

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv

COPY citygroves/frontend/flesh/package.json package.json
COPY citygroves/frontend/flesh/yarn.lock yarn.lock

RUN yarn install -d

COPY citygroves/frontend/flesh .
