FROM aux.registry.local/python-cg-ci:latest

ARG DEBIAN_VER
ARG SKAFFOLD_VER
ARG DOCKER_VER
ARG KUBECTL_VER
ARG HELM_VER
ENV CI_JOB_ID=True

RUN apt update
RUN apt install curl wget git  -y

WORKDIR /srv
COPY . plasma

WORKDIR /srv/plasma
RUN eval "$(./shell.py --dry-run)" && ./bootstrap

WORKDIR /srv/plasma/hmlet

# Install docker
RUN apt update
RUN apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt update
RUN eval "$(./shell.py test --dry-run)" && apt install docker-ce-cli=5:$HT_DOCKER_VER~3-0~debian-$HT_DEBIAN_VER -y

RUN eval "$(./shell.py test --dry-run)" && ./cluster.py install_kind
RUN eval "$(./shell.py test --dry-run)" && ./cluster.py install_kubectl
RUN eval "$(./shell.py test --dry-run)" && ./cluster.py install_skaffold
RUN eval "$(./shell.py test --dry-run)" && ./cluster.py install_helm
RUN eval "$(./shell.py test --dry-run)" && ./cluster.py install_hostess


WORKDIR /srv
RUN rm -r *
