apiVersion: v1
kind: Service
metadata:
  name: bitstamp
  namespace: dataprovs
spec:
  ports:
    - port: 8000
  type: LoadBalancer
  selector:
    app: bitstamp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitstamp
  namespace: dataprovs
  labels:
    app: bitstamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitstamp
  template:
    metadata:
      labels:
        app: bitstamp
    spec:
      hostNetwork: true
      containers:
      - name: bitstamp
        image: shangren/bitstamp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
