apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.name" . }}-db-init
  labels:
    app: {{ include "chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-init"
      labels:
        app: {{ include "chart.name" . }}
        release: "{{ .Release.fullName }}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.hooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Never
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py migrate;
              python manage.py loaddata housing/fixtures/units.yaml;
              python manage.py loaddata housing/fixtures/rooms.yaml;
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "chart.name" . }}
            - secretRef:
                name: {{ include "chart.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


