kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."$AU_REGISTRY_ADDRESS"]
    endpoint = ["http://$AU_REGISTRY_ADDRESS"]
nodes:
- role: control-plane
  image: kindest/node:v$AU_KUBERNETES_VER
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
