#!/usr/bin/env bash

. "$CG_PROJECT_ROOT"/header.sh

SHANGREN_LOCAL_IP=192.168.0.5

sudo hostess add shangren.dashboard.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.pypi.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.graylog.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.sentry.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.registry.local "$SHANGREN_LOCAL_IP"
sudo hostess add shangren.kiali.local "$SHANGREN_LOCAL_IP"

kubectl config set-cluster microk8s-cluster --server=https://"$SHANGREN_LOCAL_IP":16443 --insecure-skip-tls-verify
