---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
data:
  setup1.sql: |
    CREATE USER keycloak WITH PASSWORD 'password';
    CREATE DATABASE keycloak WITH OWNER keycloak;

    CREATE USER backend WITH PASSWORD 'password';
    CREATE DATABASE backend WITH OWNER backend;
