---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres
type: Opaque
data:
  postgresql-password: cGFzc3dvcmQ=
  postgresql-username: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  postgresql-password: cGFzc3dvcmQ=
  postgresql-username: cG9zdGdyZXM=
