---
.ht.python-base:

  cache:
    key: ${CI_COMMIT_REF_SLUG}:${CI_JOB_NAME}
    paths:
      - .venv
      - .pyenv
      - hmlet/.deps
      - hmlet/photos/flesh/.venv
  image: aux.registry.local/python-ht-ci:latest
  before_script:
    - eval "$(./shell.py --dry-run)"
    - ./bootstrap
    - cd hmlet
    - eval "$(./shell.py test --dry-run)"
