# Generated by Django 3.0.5 on 2020-04-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('caption', models.CharField(max_length=32)),
                ('image', models.ImageField(max_length=10000000.0, upload_to='.')),
                ('publish_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(max_length=10000000.0, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
