FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY tests/tester/docker docker
RUN bash docker_comm/debug/setup.sh

COPY tests/tester/flesh/Pipfile Pipfile
COPY tests/tester/flesh/Pipfile.lock Pipfile.lock

# Install common
RUN pip3 install pipenv

RUN pipenv install --system

RUN apt install curl -y

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

RUN curl -LO https://git.io/get_helm.sh
RUN bash get_helm.sh
RUN rm get_helm.sh

COPY comm/lib/shang /usr/local/lib/python3.7/site-packages/shangren
COPY datacolls datacolls
