---
variables:
  PROJECT_DIR: "$CI_PROJECT_DIR/citygroves"

include:
  - '/citygroves/.gitlab-ci-comm.yaml'
  - '/citygroves/backend/.gitlab-ci.yaml'

cg.test-devops:
  extends:
    - .python-base
#  only:
#    changes:
#      - citygroves/**/*
  stage: test
  script:
    - ./cluster.py python test_devops

cg.flake8:
  extends:
    - .python-base
#  only:
#    changes:
#      - citygroves/**/*.py
  stage: test
  script:
    - ./cluster.py python flake8
