apiVersion: skaffold/v1
kind: Config
metadata:
  name: citygroves
profiles:
  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves-local/manager
        docker:
          dockerfile: citygroves/manager/Dockerfile.local
        context: ../
        sync:
          infer:
           - 'citygroves/manager/flesh/**/*.py'
           - '**/.idea/**'
      - image: shangren.registry.local/citygroves-local/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/appgen/flesh/**/*.py'
            - '**/.idea/**'
      - image: shangren.registry.local/citygroves-local/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/frontend/flesh/**/*.ts'
            - 'citygroves/frontend/flesh/**/*.js'
            - 'citygroves/frontend/flesh/**/*.json'
            - 'citygroves/frontend/flesh/**/*.vue'
            - 'citygroves/frontend/flesh/**/*.scss'
            - '**/.idea/**'
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-local-manager
            chartPath: manager/chart
            namespace: citygroves-local
            valuesFiles:
              - manager/values/local/manager.yaml
            values:
              image: shangren.registry.local/citygroves-local/manager

          - name: citygroves-local-appgen
            chartPath: appgen/chart
            namespace: citygroves-local
            valuesFiles:
              - appgen/values/local/appgen.yaml
            values:
              image: shangren.registry.local/citygroves-local/appgen

          - name: citygroves-local-frontend
            chartPath: frontend/chart
            namespace: citygroves-local
            valuesFiles:
              - frontend/values/local/frontend.yaml
            values:
              image: shangren.registry.local/citygroves-local/frontend


  - name: stage
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves-stage/manager
        docker:
          dockerfile: citygroves/manager/Dockerfile.stage
        context: ../
      - image: shangren.registry.local/citygroves-stage/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.stage
        context: ../
      - image: shangren.registry.local/citygroves-stage/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.stage
        context: ../
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-stage-manager
            chartPath: manager/chart
            namespace: citygroves-stage
            valuesFiles:
              - manager/values/stage/manager.yaml
            values:
              image: shangren.registry.local/citygroves-stage/manager

          - name: citygroves-stage-appgen
            chartPath: appgen/chart
            namespace: citygroves-stage
            valuesFiles:
              - appgen/values/stage/appgen.yaml
            values:
              image: shangren.registry.local/citygroves-stage/appgen

          - name: citygroves-stage-frontend
            chartPath: frontend/chart
            namespace: citygroves-stage
            valuesFiles:
              - frontend/values/stage/frontend.yaml
            values:
              image: shangren.registry.local/citygroves-stage/frontend
