apiVersion: skaffold/v1
kind: Config
metadata:
  name: citygroves
profiles:
  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves/manager
        docker:
          dockerfile: citygroves/manager/Dockerfile.local
        context: ../
        sync:
          infer:
           - 'citygroves/manager/flesh/**/*.py'
           - '**/.idea/**'
      - image: shangren.registry.local/citygroves/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/appgen/flesh/**/*.py'
            - '**/.idea/**'
      - image: shangren.registry.local/citygroves/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/frontend/flesh/**/*.ts'
            - 'citygroves/frontend/flesh/**/*.js'
            - 'citygroves/frontend/flesh/**/*.json'
            - 'citygroves/frontend/flesh/**/*.vue'
            - 'citygroves/frontend/flesh/**/*.scss'
            - '**/.idea/**'
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-manager
            chartPath: manager/chart
            namespace: citygroves
            valuesFiles:
              - manager/values/local.yaml
            values:
              image: shangren.registry.local/citygroves/manager

          - name: citygroves-appgen
            chartPath: appgen/chart
            namespace: citygroves
            valuesFiles:
              - appgen/values/local.yaml
            values:
              image: shangren.registry.local/citygroves/appgen

          - name: citygroves-frontend
            chartPath: frontend/chart
            namespace: citygroves
            valuesFiles:
              - frontend/values/local.yaml
            values:
              image: shangren.registry.local/citygroves/frontend
