apiVersion: skaffold/v1
kind: Config
metadata:
  name: citygroves
profiles:
  - name: test
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves-test/backend
        docker:
          dockerfile: citygroves/backend/Dockerfile.local
        context: ../
      - image: shangren.registry.local/citygroves-test/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
        context: ../
      - image: shangren.registry.local/citygroves-test/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.local
        context: ../
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-test-backend
            chartPath: backend/chart
            namespace: citygroves-test
            valuesFiles:
              - backend/values/test/backend.yaml
            values:
              image: shangren.registry.local/citygroves-test/backend

          - name: citygroves-test-appgen
            chartPath: appgen/chart
            namespace: citygroves-test
            valuesFiles:
              - appgen/values/test/appgen.yaml
            values:
              image: shangren.registry.local/citygroves-test/appgen

          - name: citygroves-test-frontend
            chartPath: frontend/chart
            namespace: citygroves-test
            valuesFiles:
              - frontend/values/test/frontend.yaml
            values:
              image: shangren.registry.local/citygroves-test/frontend

  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves-local/backend
        docker:
          dockerfile: citygroves/backend/Dockerfile.local
        context: ../
        sync:
          infer:
           - 'citygroves/manager/flesh/**/*.py'
           - '**/.idea/**'
      - image: shangren.registry.local/citygroves-local/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/appgen/flesh/**/*.py'
            - '**/.idea/**'
      - image: shangren.registry.local/citygroves-local/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.local
        context: ../
        sync:
          infer:
            - 'citygroves/frontend/flesh/**/*.ts'
            - 'citygroves/frontend/flesh/**/*.js'
            - 'citygroves/frontend/flesh/**/*.json'
            - 'citygroves/frontend/flesh/**/*.vue'
            - 'citygroves/frontend/flesh/**/*.scss'
            - '**/.idea/**'
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-local-backend
            chartPath: backend/chart
            namespace: citygroves-local
            valuesFiles:
              - backend/values/local/backend.yaml
            values:
              image: shangren.registry.local/citygroves-local/backend

          - name: citygroves-local-appgen
            chartPath: appgen/chart
            namespace: citygroves-local
            valuesFiles:
              - appgen/values/local/appgen.yaml
            values:
              image: shangren.registry.local/citygroves-local/appgen

          - name: citygroves-local-frontend
            chartPath: frontend/chart
            namespace: citygroves-local
            valuesFiles:
              - frontend/values/local/frontend.yaml
            values:
              image: shangren.registry.local/citygroves-local/frontend

  - name: stage
    build:
      tagPolicy:
        sha256: {}
      artifacts:
      - image: shangren.registry.local/citygroves-stage/backend
        docker:
          dockerfile: citygroves/backend/Dockerfile.stage
        context: ../
      - image: shangren.registry.local/citygroves-stage/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.stage
        context: ../
      - image: shangren.registry.local/citygroves-stage/frontend
        docker:
          dockerfile: citygroves/frontend/Dockerfile.stage
        context: ../
      local:
        push: true

    deploy:
      helm:
        releases:
          - name: citygroves-stage-backend
            chartPath: backend/chart
            namespace: citygroves-stage
            valuesFiles:
              - backend/values/stage/backend.yaml
            values:
              image: shangren.registry.local/citygroves-stage/backend

          - name: citygroves-stage-appgen
            chartPath: appgen/chart
            namespace: citygroves-stage
            valuesFiles:
              - appgen/values/stage/appgen.yaml
            values:
              image: shangren.registry.local/citygroves-stage/appgen

          - name: citygroves-stage-frontend
            chartPath: frontend/chart
            namespace: citygroves-stage
            valuesFiles:
              - frontend/values/stage/frontend.yaml
            values:
              image: shangren.registry.local/citygroves-stage/frontend
