# Generated by Django 3.0 on 2020-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tenants", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="referrer",
            name="email",
            field=models.EmailField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
