# Generated by Django 3.0 on 2020-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20200109_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middle_names',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
