# Generated by Django 3.0 on 2020-01-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20200112_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_names',
            field=models.CharField(blank=True, default='', max_length=127),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EntryNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_on', models.DateField()),
                ('planned_time', models.CharField(max_length=63)),
                ('is_inspection', models.BooleanField(default=True)),
                ('is_cleaning', models.BooleanField(default=False)),
                ('is_repairs_or_maintenance', models.BooleanField(default=False)),
                ('is_pest_control', models.BooleanField(default=False)),
                ('is_showing_to_buyer', models.BooleanField(default=False)),
                ('is_valutation', models.BooleanField(default=False)),
                ('is_fire_and_rescue', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
        ),
    ]
