apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}
data:
  SENTRY_DSN: {{ .Values.sentry.dsn }}
  BITSTAMP_URL: {{ .Values.bitstamp.url }}
  SUPPORTED_CURRENCIES: "{{- range $key := .Values.bitstamp.supportedCurrencies }}{{ $key }}:{{- end }}"

