# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#image: shangren/mockexchs.bitstamp
pullPolicy: IfNotPresent

imagePullSecrets:
  - name: pullsecret

service:
  type: ClusterIP
  port: 8000

nodeSelector: {}

tolerations: []

affinity: {}

sentry:
  dsn: "http://12dbd60d73814a7f9dfc2cf9f1b101b7@sentry.sentry/3"


gmail:
  clientId: "826855560616-dleh2i9oc62cfd43l0c8rqlaps6vbpbv.apps.googleusercontent.com"
  clientSecret: "mZKwHQ5IF_-QJjEb1LLHWIpY"
  googleAuthUri: "https://accounts.google.com/o/oauth2/auth"
  googleTokenUri: "https://oauth2.googleapis.com/token"
  ownerEmail: "plasmakwazar.test@gmail.com"

formBuilderEmail: "damian.krystkiewicz@gmail.com"
