# Generated by Django 3.0 on 2019-12-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line1', models.CharField(max_length=127, null=True)),
                ('street_line2', models.CharField(max_length=127, null=True)),
                ('street_line3', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=127, null=True)),
                ('state', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('post_code', models.CharField(max_length=127, null=True)),
                ('raw_address', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('dob', models.DateField(max_length=127, null=True)),
                ('phone', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Person')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('phone', models.CharField(max_length=127)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.Address')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_ppl_to_move_in', models.IntegerField()),
                ('move_in_date', models.DateField()),
                ('guarantor_will_pay', models.BooleanField()),
                ('centerlink_will_pay', models.BooleanField()),
                ('is_employed', models.BooleanField()),
                ('have_sufficient_funds', models.BooleanField()),
                ('is_local_student', models.BooleanField()),
                ('is_international_student', models.BooleanField()),
                ('is_young_professional', models.BooleanField()),
                ('digital_signature', models.ImageField(upload_to='')),
                ('current_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.Address')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.Person')),
                ('referrers', models.ManyToManyField(to='tenants.Referrer')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.Room')),
            ],
        ),
    ]
