# Generated by Django 3.0 on 2020-01-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_person_middle_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='person',
        ),
        migrations.AddField(
            model_name='tenant',
            name='people',
            field=models.ManyToManyField(to='tenants.Person'),
        ),
    ]
