FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY dataprovs/bitstamp/docker docker
RUN bash docker_comm/debug/setup.sh

COPY dataprovs/bitstamp/flesh/Pipfile Pipfile
COPY dataprovs/bitstamp/flesh/Pipfile.lock Pipfile.lock

# Install common
RUN pip3 install pipenv

RUN pipenv install -d --system

COPY dataprovs/bitstamp/flesh .

EXPOSE 8000

CMD tail -f /dev/null
