# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: shangren/bitstamp
pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
