---

variables:
  PROJECT_DIR: "$CI_PROJECT_DIR/citygroves"
  APP_DIR: "$CI_PROJECT_DIR/citygroves/backend"

default:
  image: python:3.7.4

.base: &base
  before_script:
    - cd $PROJECT_DIR
    - source stage test
    - mkdir -p envs/test
    - echo "$KUBECONFIG" > envs/test/kubeconfig.yaml

    - cd $APP_DIR
    - source .envrc

    - cd $APP_DIR/flesh
    - source .venv/bin/activate

prepare-ci:
  stage: .pre
  cache:
    paths:
      - $APP_DIR/flesh/.venv/
  artifacts:
    paths:
      - $APP_DIR/flesh/.venv/
  before_script:
    - cd $PROJECT_DIR
    - touch .current_stage && echo "export STAGE=local" >> .current_stage

    - cd $APP_DIR
    - source .envrc

    - cd $APP_DIR/flesh
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install poetry==0.12.17
  script:
    # install poetry to separate venv so we can use it as cache for other jobs
    - poetry config settings.virtualenvs.in-project true
    - poetry install
    - cd $APP_DIR
    - deploy

flake8:
  stage: test
  <<: *base
  script:
    - local.flake8

mypy:
  stage: test
  <<: *base
  script:
    - local.mypy

test:
  stage: test
  <<: *base
  script:
    - poetry run pytest
