---

variables:
  PROJECT_DIR: "$CI_PROJECT_DIR/citygroves"
  APP_DIR: "$CI_PROJECT_DIR/citygroves/backend"

default:
  image: shangren.registry.local/python3.7.4-ci

.base: &base
  before_script:
    - cd $PROJECT_DIR
    - source stage test
    - mkdir -p envs/test
    - echo "$KUBECONFIG" > envs/test/kubeconfig.yaml

    - cd $APP_DIR
    - source .envrc

prepare-ci:
  <<: *base
  stage: .pre
  cache:
    paths:
      - $APP_DIR/flesh/.venv/
  artifacts:
    paths:
      - $APP_DIR/flesh/.venv/
  before_script:
    - cd $APP_DIR/flesh
  script:
    # install poetry to separate venv so we can use it as cache for other jobs
    - poetry config settings.virtualenvs.in-project true
    - poetry install
    - cd $APP_DIR
    - deploy

flake8:
  <<: *base
  stage: test
  script:
    - local.flake8

mypy:
  <<: *base
  stage: test
  script:
    - local.mypy

test:
  <<: *base
  stage: test
  script:
    - poetry run pytest
