---
variables:
  BACKEND_DIR: "$CI_PROJECT_DIR/citygroves/backend"

.base: &base
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv
      - .cache/
  image: shangren.registry.local/python-ci:latest
  before_script:
    - eval "$(./shell.py --dry-run)"
    - mkdir -p $HOME/.cache
    - "[[ -d .cache/pypoetry ]] && cp -r .cache/pypoetry $HOME/.cache/"
    - "[[ -d .cache/usr_local ]] && cp -r .cache/usr_local/* /usr/local/"
    - plasma.bootstrap
    - cd citygroves
    - cd backend
    - eval "$(./shell.py test --dry-run)"
    - backend.bootstrap

  after_script:
    # since caching doesn't work outside of build directory we have to move it to .cache dir
    - cd $CI_PROJECT_DIR
    - rm -rf .cache
    - mkdir .cache
    - mkdir .cache/usr_local
    - cp -r /usr/local/* .cache/usr_local
    - "[[ -d $HOME/.cache/pypoetry ]] && cp -r $HOME/.cache/pypoetry .cache/"

citygroves.backend.flake8:
  <<: *base
#  only:
#    changes:
#      - citygroves/backend/**/*.py
#      - citygroves/backend/.bin/backend.flake8
  stage: test
  script:
    - backend.flake8

citygroves.backend.test-envs:
  <<: *base
#  only:
#    changes:
#      - citygroves/backend/env_*.py
#      - citygroves/backend/shell.py
  stage: test
  script:
    - ./shell.py stage --dry-run

    - cp "$CITYGROVES_LOCAL_ENV" env_local.py
    - ./shell.py local --dry-run
    - ./shell.py test --dry-run

citygroves.backend.mypy:
  <<: *base
#  only:
#    changes:
#      - citygroves/backend/**/*.py
#      - citygroves/backend/.bin/backend.mypy
  stage: test
  script:
    - backend.mypy

citygroves.backend.test:
  <<: *base
#  only:
#    changes:
#      - citygroves/backend/**/*.py
  stage: test
  script:
    - backend.test


citygroves.backend.deploy-to-test:
  <<: *base
#  only:
#    changes:
#      - citygroves/backend/**/*

  image: shangren.registry.local/kube-ci:latest
  stage: deploy-apps
  services:
    - name: docker:18.09.9-dind
      command: ['--insecure-registry=shangren.registry.local']

  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: "tcp://127.0.0.1:2375"

  script:
    - echo "$CG_CLUSTER_ADDRESS $CG_REGISTRY_ADDRESS" >> /etc/hosts
    - cd $PROJECT_DIR
    - mkdir -p envs/test
    - cp "$TEST_KUBECONFIG" envs/test/kubeconfig.yaml
    - cd $BACKEND_DIR
    - eval "$(./shell.py test --dry-run)"
    - helm init --client-only
    - helm repo update
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CG_REGISTRY_ADDRESS
    - backend.deploy
