---

.bootstrap-backend: &bootstrap-backend |
  cd backend
  eval "$(./shell.py test --dry-run)"
  ./app.py python bootstrap_local_dev

cg.be.flake8:
  extends:
    - .cg.python-base
#  only:
#    changes:
#      - citygroves/backend/**/*.py
#      - citygroves/backend/.bin/backend.flake8
  script:
    - cd backend
    - eval "$(./shell.py test --dry-run)"
    - ./app.py python flake8

cg.be.test-devops:
  extends:
    - .cg.python-base
#  only:
#    changes:
#      - citygroves/backend/**/*
#      - citygroves/backend/shell
  script:
    - cd backend
    - eval "$(./shell.py test --dry-run)"
    - ./app.py python test_devops

cg.be.mypy:
  extends:
    - .cg.python-base
#  only:
#    changes:
#      - citygroves/backend/**/*.py
#      - citygroves/backend/.bin/backend.mypy
  script:
    - *bootstrap-backend
    - ./app.py python mypy

cg.be.test:
  extends:
    - .cg.python-base
#  only:
#    changes:
#      - citygroves/backend/flesh/**/*
  script:
    - *bootstrap-backend
    - ./app.py python test

cg.be.deploy-to-test:
  extends:
    - .cg.python-base
#  only:
#    changes:
#      - citygroves/**/*

  image: aux.registry.local/kube-cg-ci:latest
  stage: deploy-test
  services:
    - name: docker:18.09.9-dind
      command: ['--insecure-registry=citygroves.registry.test']

  variables:
    DOCKER_HOST: "tcp://127.0.0.1:2375"

  script:
    - cd $PROJECT_DIR
    - eval "$(./shell.py test --dry-run)"
    - cp "$TEST_KUBECONFIG" envs/test/kubeconfig.yaml
    - ./cluster.py add_hosts
    - helm init --client-only
    - helm repo update
    - ./cluster.py system deploy
    - ./cluster.py aux deploy
    - cd backend
    - eval "$(./shell.py test --dry-run)"
    - helm delete --purge $BE_HELM_RELEASE_NAME || true
    - ./app.py deploy
