ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH
ARG DEBIAN_VER
FROM python:$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR-slim-$DEBIAN_VER

ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH
ARG POETRY_VER

WORKDIR /srv

RUN pip install poetry==$POETRY_VER

COPY comm/docker/debug.sh /tmp/debug.sh
COPY citygroves/backend/docker /tmp/docker
RUN bash /tmp/debug.sh

COPY citygroves/backend/flesh/pyproject.toml pyproject.toml
COPY citygroves/backend/flesh/poetry.lock poetry.lock

RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project false
RUN poetry install

RUN rm * -rf
