FROM shangren.registry.local/backend-prebuild:latest

ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local
ENV APP_SRC /srv

WORKDIR /srv

# Install common
RUN pip3 install poetry

COPY citygroves/backend/flesh/pyproject.toml pyproject.toml
COPY citygroves/backend/flesh/poetry.lock poetry.lock

RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project false
RUN poetry install

COPY citygroves/backend/flesh .

COPY comm/python/pl /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/pl
COPY citygroves/comm/python/citygroves_comm /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/citygroves_comm

