ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH
ARG DEBIAN_VER
FROM aux.registry.local/local/flesh/backend-prebuild:latest

ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH
ARG POETRY_VER

WORKDIR /srv

RUN pip install poetry==$POETRY_VER

COPY citygroves/backend/flesh/pyproject.toml pyproject.toml
COPY citygroves/backend/flesh/poetry.lock poetry.lock

RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project false
RUN poetry install

COPY citygroves/backend/flesh .

COPY comm/python/pl /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/pl
COPY citygroves/comm/python/citygroves_comm /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/citygroves_comm
