FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY tests/tester/docker docker
RUN bash docker_comm/debug/setup.sh

# Install kubectl
RUN apt install curl -y
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

# Install helm
ARG HELM_VERSION
ENV HELM_NAME="helm-$HELM_VERSION-linux-386"
RUN curl -o "$HELM_NAME.tar.gz" "https://get.helm.sh/$HELM_NAME.tar.gz"
RUN tar -zxvf "$HELM_NAME.tar.gz"
RUN mv linux-386/helm /usr/local/bin/helm
RUN rm "$HELM_NAME.tar.gz"
RUN rm -r linux-386


# Install common
RUN pip3 install poetry
RUN poetry config virtualenvs.create false

COPY tests/tester/flesh/pyproject.toml pyproject.toml
COPY tests/tester/flesh/poetry.lock poetry.lock

RUN poetry install

COPY comm/lib/shang /usr/local/lib/python3.7/site-packages/shangren
COPY datacolls datacolls
