Vagrant.require_version ">= 1.7.0"


Vagrant.configure("2") do |config|
    config.vm.define "storage"
    config.vm.provider "virtualbox"
    config.vm.box = "bento/ubuntu-16.04"
    config.ssh.insert_key = true

    config.vm.define "storage" do |n|
        n.vm.hostname = "storage"
        n.vm.network :private_network, ip: "172.17.8.100"

        n.vm.provider :virtualbox do |vb, override|
            vb.name = "storage"
            vb.gui = false
            vb.memory = 1500
            vb.cpus = 1
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "deploy.yml"
                ansible.groups = {
            "local" => ["storage"],
            }
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
end
