apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-public
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.servicePublic.type }}
  {{- with .Values.servicePublic.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

