FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE local

WORKDIR /srv
COPY docker_comm docker_comm
COPY datacolls/bitstamp/docker docker
RUN bash docker_comm/debug/setup.sh

COPY datacolls/bitstamp/flesh/Pipfile Pipfile
COPY datacolls/bitstamp/flesh/Pipfile.lock Pipfile.lock

# Install common
RUN pip3 install pipenv

RUN pipenv install -d --system
COPY datacolls/bitstamp/flesh .

EXPOSE 8000

CMD watchmedo shell-command --patterns="*.py" --command="python prov.py"
