apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}
data:
  config.ts: |
    export const Config =
    {
      backend: {
        apiUrl: "{{ .Values.backend.apiUrl }}",
      },
      keycloak: {
        url: "{{ .Values.keycloak.url }}"
      }
    };
