kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentbit-config
  namespace: graylog
  labels:
    app: fluent-bit
    chart: fluent-bit-2.7.1
    heritage: Tiller
    release: graylog-fluentbit
data:
  parsers.conf: |
    [PARSER]
        Name   json2
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  fluent-bit.conf: |
    [OUTPUT]
        Name  gelf
        Match *
        Host  graylog-tcp
        Port  12201
        Mode tcp
        Gelf_Short_Message_Key short_message

    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers_custom.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            json2
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              Off
        Annotations         Off

    [FILTER]
        Name nest
        Match *
        Operation lift
        Nested_under kubernetes

    [FILTER]
        Name modify
        Match *
        Rename log short_message
        Add version 1.0

    [FILTER]
        Name record_modifier
        Match *
        Remove_key annotations
        Remove_key labels
        Remove_key kubrnetes
        Remove_key kubernetes
