FROM citygroves.registry.local/local/appgen-prebuild:latest

WORKDIR /srv

RUN pip3 install poetry==1.0.3

COPY citygroves/appgen/flesh/pyproject.toml pyproject.toml
COPY citygroves/appgen/flesh/poetry.lock poetry.lock

RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.in-project false
RUN poetry install

COPY citygroves/appgen/flesh .

COPY comm/python/pl /usr/local/lib/python3.8/pl
COPY citygroves/comm /usr/local/lib/python3.8/cg_comm