ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH
ARG DEBIAN_VER
FROM python:$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR-slim-$DEBIAN_VER

ARG PYTHON_VER_MAJOR
ARG PYTHON_VER_MINOR
ARG PYTHON_VER_PATCH

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV SHELL /bin/bash
ENV STAGE stage

WORKDIR /srv
COPY comm/docker/debug.sh /tmp/debug.sh
COPY citygroves/appgen/docker /tmp/docker
RUN bash /tmp/debug.sh

# Install common
RUN pip3 install poetry
RUN poetry config virtualenvs.create false

COPY citygroves/appgen/flesh/pyproject.toml pyproject.toml
COPY citygroves/appgen/flesh/poetry.lock poetry.lock

RUN poetry install
COPY citygroves/appgen/flesh .
COPY comm/python/plasma /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/plasma
COPY citygroves/comm/python/citygroves_comm /usr/local/lib/python$PYTHON_VER_MAJOR.$PYTHON_VER_MINOR/citygroves_comm
