apiVersion: skaffold/v1
kind: Config
metadata:
  name: citygroves
profiles:
  - name: test
    build:
      tagPolicy:
        envTemplate:
          template: "{{.CG_IMAGE_NAME}}:{{.CG_IMAGE_TAG}}"
      artifacts:
      - image: citygroves.registry.test/flesh/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
          buildArgs:
            PYTHON_VER_MAJOR: '{{.CG_PYTHON_VER_MAJOR}}'
            PYTHON_VER_MINOR: '{{.CG_PYTHON_VER_MINOR}}'
            PYTHON_VER_PATCH: '{{.CG_PYTHON_VER_PATCH}}'
            DEBIAN_VER: '{{.CG_DEBIAN_VER}}'
        context: ../../
      local:
        push: false

    deploy:
      helm:
        releases:
          - name: citygroves-appgen
            chartPath: chart
            namespace: flesh
            valuesFiles:
              - values/test/appgen.yaml
            values:
              image: citygroves.registry.test/flesh/appgen

  - name: local
    build:
      tagPolicy:
        envTemplate:
          template: "{{.CG_IMAGE_NAME}}:{{.CG_IMAGE_TAG}}"
      artifacts:
      - image: citygroves.registry.local/flesh/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.local
          buildArgs:
            PYTHON_VER_MAJOR: '{{.CG_PYTHON_VER_MAJOR}}'
            PYTHON_VER_MINOR: '{{.CG_PYTHON_VER_MINOR}}'
            PYTHON_VER_PATCH: '{{.CG_PYTHON_VER_PATCH}}'
            DEBIAN_VER: '{{.CG_DEBIAN_VER}}'
        context: ../../
        sync:
          infer:
            - 'citygroves/appgen/flesh/**/*.py'
            - '**/.idea/**'
      local:
        push: false

    deploy:
      helm:
        releases:
          - name: citygroves-appgen
            chartPath: chart
            namespace: flesh
            valuesFiles:
              - values/local/appgen.yaml
            values:
              image: citygroves.registry.local/flesh/appgen

  - name: stage
    build:
      tagPolicy:
        envTemplate:
          template: "{{.CG_IMAGE_NAME}}:{{.CG_IMAGE_TAG}}"
      artifacts:
      - image: citygroves.registry.stage/flesh/appgen
        docker:
          dockerfile: citygroves/appgen/Dockerfile.stage
          buildArgs:
            PYTHON_VER_MAJOR: '{{.CG_PYTHON_VER_MAJOR}}'
            PYTHON_VER_MINOR: '{{.CG_PYTHON_VER_MINOR}}'
            PYTHON_VER_PATCH: '{{.CG_PYTHON_VER_PATCH}}'
            DEBIAN_VER: '{{.CG_DEBIAN_VER}}'
        context: ../../
      local:
        push: false

    deploy:
      helm:
        releases:
          - name: citygroves-stage-appgen
            chartPath: chart
            namespace: flesh
            valuesFiles:
              - values/stage/appgen.yaml
            values:
              image: citygroves.registry.stage/flesh/appgen
